name: CI for Next.js with Playwright

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Step 3: Load environment variables from GitHub Secrets
      - name: Set up environment variables
        run: echo "${{ secrets.ENV_FILE }}" | tr ' ' '\n' > .env

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 6: Run ESLint to check for syntax and style errors
      - name: Run ESLint
        run: npm run lint

      # Step 7: Start the application server
      - name: Start the server
        run: npm run start &
        env:
          PORT: 5432

      # Step 8: Wait for the server to be ready
      - name: Wait for server to be ready
        run: npx wait-on https://campus-careers-app.vercel.app && sleep 5

      # Step 10: Run Playwright tests
      - name: Run Playwright tests
        run: npm run playwright-ci

      # Step 11: Upload Playwright report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          